package main

import (
	"fmt"
	"log"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// writeReservations realises the desired state as dnsmasq host records.
//
// One file per blade under dhcp-hostsdir, because dnsmasq reads that
// directory on a reload and a file is the smallest thing that can be replaced
// without touching the rest.
//
// CAREFUL: such a file holds ONLY what would otherwise stand to the right of
// "dhcp-host=". Include the prefix and dnsmasq reports "bad hex constant" and
// drops the line silently — the reservation then has no effect at all, while
// everything above it reports success.
func (s *site) writeReservations(d *desired) error {
	if err := os.MkdirAll(s.cfg.HostsDir, 0o755); err != nil {
		return fmt.Errorf("directory %s: %w", s.cfg.HostsDir, err)
	}
	var written, removed []string
	want := map[string]bool{}

	for _, b := range d.Blades {
		if b.MAC == "" || b.IP == "" || b.Hostname == "" {
			continue
		}
		if err := validReservation(b.MAC, b.Hostname, b.IP); err != nil {
			s.note(b.Serial, "warn", "reservation rejected: "+err.Error())
			continue
		}
		name := "blade-" + b.Serial + ".conf"
		want[name] = true

		// The netboot switch. The Raspberry Pi bootloader only netboots when
		// DHCP option 43 carries "Raspberry Pi Boot", and dnsmasq offers that
		// only to hosts tagged for it. Without the tag the netboot fails at
		// once and the bootloader falls through to the NVMe — which is how a
		// finished blade boots locally while a reimage stays a decision
		// someone makes centrally.
		tag, why := "", "boots from the NVMe"
		if b.Netboot {
			tag, why = "set:bootnet,", "install requested – boots over the network"
		}
		body := fmt.Sprintf(
			"# Rookery – generated by rookery-site, do not edit by hand\n"+
				"# Blade %s  BladeRunner %s  Slot %d\n"+
				"# %s\n"+
				"%s,%s%s,%s,infinite\n",
			b.Serial, b.Rack, b.Slot, why, b.MAC, tag, b.Hostname, b.IP)

		path := filepath.Join(s.cfg.HostsDir, name)
		if old, err := os.ReadFile(path); err == nil && string(old) == body {
			continue
		}
		if s.dry {
			written = append(written, name+" (dry run)")
			continue
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		written = append(written, name)
	}

	// Files for blades that no longer stand here — moved, removed, or taken
	// out of their slot.
	entries, _ := os.ReadDir(s.cfg.HostsDir)
	for _, e := range entries {
		n := e.Name()
		if !strings.HasPrefix(n, "blade-") || !strings.HasSuffix(n, ".conf") || want[n] {
			continue
		}
		if s.dry {
			removed = append(removed, n+" (dry run)")
			continue
		}
		if err := os.Remove(filepath.Join(s.cfg.HostsDir, n)); err == nil {
			removed = append(removed, n)
		}
	}

	sort.Strings(written)
	sort.Strings(removed)
	if len(written) == 0 && len(removed) == 0 {
		return nil
	}
	log.Printf("reservations: %d written, %d removed", len(written), len(removed))
	s.note("", "info", fmt.Sprintf("reservations: %d written, %d removed",
		len(written), len(removed)))
	if s.dry {
		return nil
	}
	if err := reloadDnsmasq(); err != nil {
		return err
	}
	return nil
}

// reloadDnsmasq makes dnsmasq re-read the host records. A reload, not a
// restart: a restart drops every lease, and a SIGHUP is also the only way to
// make dnsmasq forget a record it has already read — entries from a
// hostsdir are added, never replaced.
func reloadDnsmasq() error {
	out, err := exec.Command("sudo", "-n", "systemctl", "reload", "dnsmasq").CombinedOutput()
	if err != nil {
		return fmt.Errorf("dnsmasq not reloaded: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// validReservation checks what dnsmasq would otherwise reject silently.
func validReservation(mac, host, ip string) error {
	if _, err := net.ParseMAC(mac); err != nil {
		return fmt.Errorf("MAC %q: %w", mac, err)
	}
	if net.ParseIP(ip) == nil || strings.Contains(ip, ":") {
		return fmt.Errorf("IPv4 %q invalid", ip)
	}
	if host == "" || len(host) > 63 {
		return fmt.Errorf("host name %q invalid", host)
	}
	for i := 0; i < len(host); i++ {
		c := host[i]
		ok := (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '-'
		if !ok {
			return fmt.Errorf("host name %q: %q is not allowed", host, string(c))
		}
	}
	if host[0] == '-' || host[len(host)-1] == '-' {
		return fmt.Errorf("host name %q may not start or end with a hyphen", host)
	}
	return nil
}
